# Name of your site (displayed in the header)
name: Def.Center

# Short bio or description (displayed in the header)
description: Консультация по любым вопросам информационной безопасности
---
exclude: ['Gemfile', 'Gemfile.lock', 'README.markdown']
permalink: pretty
